### Numpy Arrays

In [1]:
!pip install numpy

In [12]:
my_list = [1,2,3,]

In [8]:
my_list

[1, 2, 3, 'new']

In [14]:
import numpy as np

In [15]:
arr = np.array(my_list)

In [16]:
arr

array([1, 2, 3])

In [18]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [19]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
range(0,10)

range(0, 10)

In [22]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [25]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((3,3)) #rowXcolum

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.eye(3) #identical matrics row colum same

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.linspace(0,5,10) #starting, stop, how many data i want 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [35]:
np.linspace(100,500,10)

array([100.        , 144.44444444, 188.88888889, 233.33333333,
       277.77777778, 322.22222222, 366.66666667, 411.11111111,
       455.55555556, 500.        ])

In [36]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [37]:
np.random.rand(5) #alwayy give value from 0-1

array([0.7291105 , 0.34869482, 0.54080156, 0.17793136, 0.15871414])

In [38]:
np.random.rand(5,7)

array([[0.12572776, 0.21813187, 0.77846957, 0.98456006, 0.22478949,
        0.00643264, 0.26570958],
       [0.09284324, 0.17187445, 0.22892538, 0.21032232, 0.03732129,
        0.8375606 , 0.29110172],
       [0.64203225, 0.74695497, 0.03763245, 0.01904502, 0.6891151 ,
        0.06950859, 0.23963775],
       [0.10585375, 0.67109246, 0.22255927, 0.7098551 , 0.18197125,
        0.60637478, 0.04383942],
       [0.46378286, 0.42207754, 0.87489693, 0.76371438, 0.08558232,
        0.1930137 , 0.24159912]])

In [40]:
np.random.rand(3,5)

array([[6.16887476e-06, 9.15493103e-01, 7.39952472e-01, 1.17439696e-01,
        2.71241962e-01],
       [6.92349304e-01, 6.61352609e-02, 7.94039045e-01, 3.68570618e-01,
        3.83544070e-01],
       [1.24805094e-01, 4.80787914e-01, 3.35857832e-01, 1.47112591e-01,
        7.72557643e-01]])

In [42]:
np.random.randint(1,100)

15

In [43]:
np.random.randint(1,100,30)

array([56, 28, 52, 36, 26, 63, 13,  6, 61,  5, 40, 46, 47, 80, 56, 10, 56,
       50, 31, 60, 22, 48, 82, 79, 70, 28, 50, 43, 45, 22])

In [48]:
arr= np.arange(1,100,2) #start,stop,step

In [49]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [50]:
ranarr= np.random.randint(0,50,10)

In [51]:
ranarr

array([10, 33, 39,  9, 11, 32, 23, 17, 21,  6])

In [52]:
ranarr.shape

(10,)

In [53]:
ranarr.reshape(5,2)

array([[10, 33],
       [39,  9],
       [11, 32],
       [23, 17],
       [21,  6]])

In [54]:
arr.shape

(50,)

In [55]:
arr.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [56]:
ranarr.max()

np.int64(39)

In [59]:
print (ranarr.max())

39


In [60]:
ranarr.min()

np.int64(6)

In [61]:
print (ranarr.min()) 

6


In [62]:
ranarr.argmax() #max index

np.int64(2)

In [63]:
print (ranarr.argmax()) 

2


In [64]:
ranarr.argmin()

np.int64(9)

In [65]:
ranarr

array([10, 33, 39,  9, 11, 32, 23, 17, 21,  6])

In [66]:
type(arr)

numpy.ndarray

In [68]:
arr.dtype

dtype('int64')

### Numpy Array indexing

In [70]:
arr = np.arange(0,10)

In [71]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr[8]

np.int64(8)

In [73]:
arr[1:5] #starting index,stop position

array([1, 2, 3, 4])

In [74]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [75]:
arr[0:5] = 100

In [76]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [78]:
arr2= np.arange(0,10)

In [79]:
s_arr=arr2[0:5]

In [80]:
s_arr

array([0, 1, 2, 3, 4])

In [81]:
s_arr[::] = 100

In [82]:
s_arr

array([100, 100, 100, 100, 100])

### copy array

In [83]:
arr_copy=arr2.copy()

In [84]:
arr_copy[0:5] = 500

In [85]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [86]:
arr_copy

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

### 2D Array

In [88]:
arr_2d =np.array([[10,25,75],[37,49,21],[8,34,21]])

In [89]:
arr_2d

array([[10, 25, 75],
       [37, 49, 21],
       [ 8, 34, 21]])

In [90]:
arr_2d[0][1] #rXc #first row 2nd value

np.int64(25)

In [91]:
print(np.int64(25))

25


In [93]:
arr_2d[1][2] #2nd row 3rd value

np.int64(21)

In [94]:
print(arr_2d[1][2])

21


In [95]:
arr_2d[:2] #ROW

array([[10, 25, 75],
       [37, 49, 21]])

In [96]:
arr_2d[:2,1:]

array([[25, 75],
       [49, 21]])

In [97]:
arr_2d[1:,:2]

array([[37, 49],
       [ 8, 34]])

In [98]:
arr2 = np.arange(0,10)

In [99]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr2>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [101]:
arr2[arr2 > 5]

array([6, 7, 8, 9])

In [102]:
arr_2d= np.arange(50).reshape(5,10)

In [103]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [104]:
arr_2d[2:4 , 5:7]

array([[25, 26],
       [35, 36]])

### Numpy Operation

In [106]:
arr=np.arange(0,11)

In [107]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr+ arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [109]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [110]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [111]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [112]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [114]:
arr/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [115]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [116]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])